# Generated by Django 3.2 on 2021-04-23 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_text', models.TextField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
