# Generated by Django 3.2 on 2021-04-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='question_text',
            new_name='note_text',
        ),
    ]
