# Generated by Django 3.2 on 2021-04-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_question_text_note_note_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_text',
        ),
    ]
